package summit.summitexpenseprj;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApprovalDO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ApprovalDO() {
    }

}