package summit.summitexpenseprj;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerProfileDO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String id;
   private java.lang.String rating;
   private java.lang.String recentinterestin;
   private java.lang.String currentpromotion;
   private java.lang.String trigger;

   private java.lang.String servicereco;

   public CustomerProfileDO()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getRating()
   {
      return this.rating;
   }

   public void setRating(java.lang.String rating)
   {
      this.rating = rating;
   }

   public java.lang.String getRecentinterestin()
   {
      return this.recentinterestin;
   }

   public void setRecentinterestin(java.lang.String recentinterestin)
   {
      this.recentinterestin = recentinterestin;
   }

   public java.lang.String getCurrentpromotion()
   {
      return this.currentpromotion;
   }

   public void setCurrentpromotion(java.lang.String currentpromotion)
   {
      this.currentpromotion = currentpromotion;
   }

   public java.lang.String getTrigger()
   {
      return this.trigger;
   }

   public void setTrigger(java.lang.String trigger)
   {
      this.trigger = trigger;
   }

   public java.lang.String getServicereco()
   {
      return this.servicereco;
   }

   public void setServicereco(java.lang.String servicereco)
   {
      this.servicereco = servicereco;
   }

   public CustomerProfileDO(java.lang.String id, java.lang.String rating,
         java.lang.String recentinterestin, java.lang.String currentpromotion,
         java.lang.String trigger, java.lang.String servicereco)
   {
      this.id = id;
      this.rating = rating;
      this.recentinterestin = recentinterestin;
      this.currentpromotion = currentpromotion;
      this.trigger = trigger;
      this.servicereco = servicereco;
   }

}